jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "status: waiting for author"

name: Add Label On Review Submitted

on:
  pull_request_review:
    types: [submitted]

permissions: write-all
