jobs:
  remove_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: "status: waiting for author"

name: Remove Label On Review Requested

on:
  pull_request:
    types: [review_requested]

permissions:
  pull-requests: write
